### PR TITLE
Bigcleanup

### PR DESCRIPTION
**Pull request by rumblesan**
So this is a big pull request with a bunch of cleanup and formatting stuff.

a few chunks of code removed, lots of whitespace fixes, moving some things around to make everything a bit clearer.

Primarily this was just so I could get stuck back into all the code and get it back in my head again.

Tested in chrome and firefox on OSX, going to test on windows when I get a chance

### CODE REVIEW

**Comment by davidedc** [comment]
There seems to be a glitch - the reset button doesn't clear the screen.

screen shot 2015-06-21 at 10 22 01

**Comment by rumblesan** [comment]
is that happening consistently for you? I'm not able to reproduce it on chrome or firefox

**Comment by davidedc** [comment]
wait I download the timekeeper-cleanup instead of the bigcleanup branch, sorry, will give i a go now.

**Comment by davidedc** [comment]
[just deleted misleading posts above]

Found one minor glitch - clicking on the "Livecodelab 2.0" box on the top-left used to bring up a small dialog, it doesn't anymore.

**Comment by rumblesan** [comment]
ah ha, good spot. just fixed it. I'm going to give this a go on a windows machine now. and assuming there's nothing terribly broken with it I'd like to get it merged

**Comment by davidedc** [comment]
cool let me know how it goes.

**Comment by rumblesan** [comment]
ok, Chrome on windows works just fine. both sound and visuals.

On IE11, it's not so great :( the framerate is pretty poor, hanging around 17 to 20 fps. The audio doesn't work. This does seem to be exactly the same as when running against the currently released version though, so nothing seems to be broken that wasn't already

**Comment by davidedc** [comment]
K if it's same as current release let's merge and take it from there then.

**Comment by rumblesan** [comment]
awesome, some of this will help make some of the other stuff I have in mind easier

**Pull request merged**
