### PR TITLE
Timekeeper cleanup

### PR DESCRIPTION
**Pull request by rumblesan**
So these changes should make the time keeper and sound system a bit more solid.

There's still some work to do
* This uses the Web Audio API, so there's not yet support for IE
* The syncing with the pulse client might not be up to scratch, it needs more testing.

There's also a question about how the BPM updating should work. Currently it works fine, but it will update at the next quarter note (i.e. every run of the beatLoop callback). This might not be the desired behaviour, so we should figure out what is

### CODE REVIEW

**Comment by rumblesan** [comment]
So I'm going to start having a look at this again as I'd really like to get it merged.
I'm doing some work to move over to using browserify to build LCL, as it's much easier and simpler than using require I've found, but I'm having issues with some of the sound libraries using globals, so simplifying this might make the task easier.
Were there any issues with this branch that still needed fixing?

**Comment by rumblesan** [comment]
just rebased this onto master and it seems to be working pretty solidly

**Comment by rumblesan** [comment]
Also just tried it in firefox and it's fine as well. This is on OSX though, not tried windows.

**Comment by davidedc** [comment]
So here were my issues with this pull back then:

 - it ruled out IE (the latest "Edge" version probably has web audio support so it will be OK at that time in the future when normal people will be able to install Edge)
 - it doesn't free the main thread from the triggering of the sample playing (which would be possible to do with web audio and would be a big win)
 - it contained a couple of changes that are useful independently from the rest of the changes

That, and the fact that sound support has been traditionally very fiddly to implement and test.

So that's why this pull has been hanging...

If this came in as an addendum (rather than a replacement) to the already existing library solutions, and it did make use of the webaudio "start playing the sample while the main thread is doing other things", then this would be just a win-win to merge.

It's the idea of regressing on IE support and having to test the fiddly part and yet to _still_ have the contention problem over the main thread (between graphics and sample playback)... it made this pull request "easy to postpone" for me...

**Comment by rumblesan** [comment]
so IE support should be fine now. I added buzz back in and this will fall back to that if the web audio API isn't available. I'll give it more of a poke tomorrow when I can more properly assess the ins and outs. I actually have access to a windows machine I realise, so I can test on that haha. will let you know, but if it all seems fine then I'd like to get it merged. the sound system will be a whole lot simpler

**Comment by rumblesan** [comment]
ok, this has been rebased onto master again after the cleanup PR merge.

I've now fixed the issue with reset not actually clearing the screen. Also made sure it works when the previous program was using paintOver animation mode

**Comment by rumblesan** [comment]
turns out the old screen clearing code I removed is actually pretty important. removed that commit

**Comment by rumblesan** [comment]
tested this on chrome, firefox and safari on OSX, and also on chrome and firefox on windows. All working fine.

IE11 sound is still broken, but I think that's going to be a bigger investigation and I'm tempted to say that we should merge this and then start investigating that. thoughts?

**Comment by davidedc** [comment]
let me give it some hell. Is there a way we can test the midi input?

**Comment by davidedc** [comment]
works for me too.

One thing though, we have a "grunt releasebuild --language=vX" build option in order to only include one language or the other. The build system would then automatically eliminate the "dead code" caused by the flag, hence including the minimum code needed for only one language or the other.

I liked that option as I could build and push publicly the build for v1 only (for the moment)... can it be added back again?

**Comment by davidedc** [comment]
(I didn't test the midi input by the way)

**Comment by rumblesan** [comment]
So the language build option I don't actually think is so much use.
I'd rather just always have both languages available until we can retire v1
Guy

**Comment by davidedc** [comment]
I don't think we should expose users to the selection of two similar languages though... that means that if I merge this we can't publish master until we retire v1? I don't think we can know for sure when that is?

**Comment by davidedc** [comment]
ah realised buildTimeOptions are already removed in master, gonna merge this then. Will worry about pre-baking only one language when we get close to a release.

**Comment by rumblesan** [comment]
so I have some plans around improving the build system again. specifically, moving away from grunt and requirejs to browserify. It will be much simpler once I'm done, and we can have a much improved buildTimeOptions style system.

**Pull request merged**
